// <auto-generated />
namespace HealthStation_Test.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addqty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addqty));
        
        string IMigrationMetadata.Id
        {
            get { return "202004111903598_addqty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
